version: '3'

services:
  mariadb:
    container_name: mariadb
    volumes:
      - datadb:/var/lib/mysql
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure # "on-failure", container will be restarted

  wordpress:
    container_name: wordpress
    env_file:
      - .env
    volumes:
    - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:    # wordpress will be started after mariadb
      - mariadb
    restart: on-failure

  nginx:           # with TLSv.1.2
    container_name: nginx # name of the container
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
        - .env
    ports:
      - "443:443"
    restart: on-failure


## VOLUME CHECK

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/emcariot/data/wordpress'
  datadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/emcariot/data/mysql'

#network part
networks:
    inception:
      driver: bridge
