version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    volumes: 
      - datadb:/var/lib/mysql
    networks:
      - inception
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
      # MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: on-failure # "on-failure", container will be restarted 
    expose:
      - "3306"



  nginx:           # with TLSv.1.2
    image: nginx
    container_name: nginx # name of the container
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
        - .env
        # MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        # MYSQL_DATABASE: ${MYSQL_DATABASE}
        # MYSQL_USER: ${MYSQL_USER}
        # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
      # DB_NAME: ${DB_NAME}
      # DB_USER: ${DB_USER}
      # DB_PASSWORD: ${DB_PASSWORD}
      # DB_HOST: ${DB_HOST}

      # WP_ADMIN_LOGIN: ${WP_ADMIN_LOGIN}
      # WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      # WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      # MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
    - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:    # wordpress will be started after mariadb
      - mariadb
    restart: on-failure
    expose: 
      - "9000"


## VOLUME CHECK

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/emcariot/data/wordpress'
  datadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/emcariot/data/mysql'



#network part
networks:
    inception:
